export default {
    list: [
        // {
        //     id: 1,
        //     name: "fake connect",
        //     type: "",
        //     active: false,
        //     owner: "You",
        // },
        // {
        //     id: 2,
        //     name: "Almedsdassdasd.cz",
        //     type: "shared",
        //     active: false,
        //     owner: "Someone else",
        // },
        // {
        //     id: 3,
        //     name: "Pininasdsdd.cz",
        //     type: "",
        //     active: false,
        //     owner: "You",
        // },
        // {
        //     id: 4,
        //     name: "Plan-k.cz",
        //     type: "",
        //     active: true,
        //     owner: "You",
        // },
        // {
        //     id: 5,
        //     name: "25let.cz",
        //     type: "",
        //     active: false,
        //     owner: "You",
        // },
    ],
    localFiles: [
        // {
        //     id: 1,
        //     name: "folder 1",
        //     size: 3673654,
        //     type: "folder",
        // },
        // {
        //     id: 2,
        //     name: "folder asd 1",
        //     size: 367483654,
        //     type: "file",
        //     extension: "psd",
        // },
        // {
        //     id: 3,
        //     name: "folder  asdasdasd 1",
        //     size: 367563654,
        //     type: "file",
        //     extension: "html",
        // },
        // {
        //     id: 4,
        //     name: "asdasdolder 4",
        //     size: 36754,
        //     type: "folder",
        // },
    ],
    localCurrentFolder: "",
    remoteFiles: [
        // {
        //     id: 1,
        //     name: "folder 1",
        //     size: 3673654,
        //     type: "folder",
        // },
        // {
        //     id: 2,
        //     name: "folder asd 1",
        //     size: 367483654,
        //     type: "file",
        //     extension: "psd",
        // },
        // {
        //     id: 3,
        //     name: "folder  asdasdasd 1",
        //     size: 367563654,
        //     type: "file",
        //     extension: "html",
        // },
        // {
        //     id: 4,
        //     name: "asdasdolder 4",
        //     size: 36754,
        //     type: "folder",
        // },
    ],
    remoteCurrentFolder: "",
    currentBoard: null,
    status: "idle",
    activePanel: "transfer",
    searched: "",
    queue: [
        // {
        //     name: "some-file.html",
        //     fromFolder: "georgymarchuk/Desktop/whatever",
        //     toFolder: "georgymarchuk/Desktop/whatever",
        //     upload: true,
        //     size: 367563654,
        //     priority: 1,
        //     progress: 0.1,
        //     transfered: 23213,
        //     inProgress: true,
        // },
        // {
        //     name: "some-other-file.html",
        //     fromFolder: "georgymarchuk/Desktop/whatever",
        //     toFolder: "georgymarchuk/Desktop/whatever",
        //     upload: true,
        //     size: 36563654,
        //     priority: 3,
        //     progress: 0.1,
        // },
        // {
        //     name: "some-file.html",
        //     fromFolder: "georgymarchuk/Desktop/whatever",
        //     toFolder: "georgymarchuk/Desktop/whatever",
        //     upload: "",
        //     size: 36756354,
        //     priority: 5,
        //     progress: 0.1,
        //     inProgress: false,
        // },
    ],
    queueStatus: "played",
    settings: {
        theme: "default",
        animations: "default",
    },
    log: []
}